# Generated by Django 4.1.3 on 2022-12-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamer',
            name='in_twitch_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='streamer',
            name='mastodon_id',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='streamer',
            name='on_mastodon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='streamer',
            name='on_twitch',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='streamer',
            name='twitch_id',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='streamer',
            name='twitch_uri_in_mastodon_fields',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='twitch_login',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='twitch_name',
            field=models.TextField(null=True, unique=True),
        ),
    ]
