# Generated by Django 4.1.3 on 2022-12-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0002_streamer_in_twitch_team_streamer_mastodon_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamer',
            name='discord_id',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='streamer',
            name='on_discord',
            field=models.BooleanField(default=False),
        ),
    ]
