# Generated by Django 4.1.3 on 2022-12-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0003_streamer_discord_id_streamer_on_discord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamer',
            name='on_twitch',
            field=models.BooleanField(default=False),
        ),
    ]
