# Generated by Django 4.1.3 on 2022-12-10 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streamer', '0004_alter_streamer_on_twitch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamer',
            name='discord_id',
        ),
        migrations.RemoveField(
            model_name='streamer',
            name='in_twitch_team',
        ),
        migrations.RemoveField(
            model_name='streamer',
            name='mastodon_id',
        ),
        migrations.RemoveField(
            model_name='streamer',
            name='on_discord',
        ),
        migrations.RemoveField(
            model_name='streamer',
            name='on_mastodon',
        ),
        migrations.RemoveField(
            model_name='streamer',
            name='on_twitch',
        ),
        migrations.RemoveField(
            model_name='streamer',
            name='twitch_id',
        ),
        migrations.RemoveField(
            model_name='streamer',
            name='twitch_login',
        ),
        migrations.RemoveField(
            model_name='streamer',
            name='twitch_name',
        ),
        migrations.RemoveField(
            model_name='streamer',
            name='twitch_uri_in_mastodon_fields',
        ),
        migrations.AddField(
            model_name='streamer',
            name='identity',
            field=models.CharField(default='none', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streamer',
            name='shramp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='streamer',
            name='shrampybot_announce',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='streamer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StreamerTwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('twitch_id', models.CharField(max_length=255, null=True, unique=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('streamer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='streamer.streamer')),
            ],
        ),
        migrations.CreateModel(
            name='StreamerMastodon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastodon_id', models.CharField(max_length=255, unique=True)),
                ('acct', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('primary_twitch_url', models.CharField(max_length=255, null=True)),
                ('derived_twitch_id', models.CharField(max_length=255, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('streamer', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='streamer.streamer')),
                ('twitch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='streamer.streamertwitch')),
            ],
        ),
        migrations.CreateModel(
            name='StreamerGSGFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual_name', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('twitch_url', models.CharField(max_length=255, null=True)),
                ('irl_location', models.CharField(max_length=255, null=True)),
                ('now', models.CharField(max_length=255, null=True)),
                ('next', models.CharField(max_length=255, null=True)),
                ('later', models.CharField(max_length=255, null=True)),
                ('notes', models.TextField(null=True)),
                ('derived_twitch_id', models.CharField(max_length=255, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='streamer.streamer')),
                ('twitch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='streamer.streamertwitch')),
            ],
        ),
        migrations.CreateModel(
            name='StreamerDiscord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=255, unique=True)),
                ('discord_name_in_guild', models.CharField(max_length=255, unique=True)),
                ('parsed_twitch_url', models.CharField(max_length=255, unique=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('streamer', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='streamer.streamer')),
            ],
        ),
    ]
