# Generated by Django 4.1.3 on 2022-12-10 18:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0005_remove_streamer_discord_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamergsgfile',
            old_name='email',
            new_name='e_mail',
        ),
        migrations.RemoveField(
            model_name='streamergsgfile',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='streamergsgfile',
            name='derived_twitch_id',
        ),
        migrations.RemoveField(
            model_name='streamergsgfile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='streamergsgfile',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='streamergsgfile',
            name='streamer',
        ),
        migrations.RemoveField(
            model_name='streamergsgfile',
            name='twitch',
        ),
        migrations.AddField(
            model_name='streamergsgfile',
            name='alt_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='streamergsgfile',
            name='guid',
            field=models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False),
        ),
    ]
