# Generated by Django 4.1.3 on 2022-12-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0006_rename_email_streamergsgfile_e_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamergsgfile',
            name='visual_name',
            field=models.CharField(max_length=255),
        ),
    ]
