# Generated by Django 4.1.3 on 2022-12-10 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0007_alter_streamergsgfile_visual_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamertwitch',
            old_name='name',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='streamer',
            name='guild_member',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='streamer',
            name='retired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='streamer',
            name='retired_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='streamergsgfile',
            name='streamer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='streamer.streamer'),
        ),
        migrations.AddField(
            model_name='streamergsgfile',
            name='twitch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='streamer.streamertwitch'),
        ),
        migrations.AddField(
            model_name='streamertwitch',
            name='account_type',
            field=models.CharField(choices=[('', 'User'), ('staff', 'Staff'), ('global_mod', 'Global Mod'), ('admin', 'Admin')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='streamertwitch',
            name='broadcaster_type',
            field=models.CharField(choices=[('', 'Basic'), ('affiliate', 'Affiliate'), ('partner', 'Partner')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='streamertwitch',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='streamertwitch',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='streamertwitch',
            name='offline_image_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='streamertwitch',
            name='profile_image_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='streamertwitch',
            name='twitch_created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='shrampybot_announce',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
