# Generated by Django 4.1.3 on 2022-12-10 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0008_rename_name_streamertwitch_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamergsgfile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streamergsgfile',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
