# Generated by Django 4.1.3 on 2022-12-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0009_streamergsgfile_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamer',
            name='og_shramp',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
