# Generated by Django 4.1.3 on 2022-12-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0011_rename_twitch_streamergsgfile_twitch_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamer',
            name='guild_member',
        ),
        migrations.RemoveField(
            model_name='streamer',
            name='og_shramp',
        ),
        migrations.RemoveField(
            model_name='streamer',
            name='shramp',
        ),
        migrations.AddField(
            model_name='streamer',
            name='guild_status',
            field=models.CharField(choices=[('fry', 'Shrimp Fry (Pre-event)'), ('shrimp', 'Shrimp (1+ events)'), ('shramp', 'Shramp (3+ events)'), ('scampi', 'Scampi Shramp (OG)')], default='fry', max_length=30),
        ),
    ]
