# Generated by Django 4.1.3 on 2022-12-12 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitchapp', '0001_initial'),
        ('streamer', '0012_remove_streamer_guild_member_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StreamerGSGFile',
            new_name='StreamerAct',
        ),
        migrations.RemoveField(
            model_name='streamermastodon',
            name='streamer',
        ),
        migrations.RemoveField(
            model_name='streamermastodon',
            name='twitch_account',
        ),
        migrations.RemoveField(
            model_name='streamertwitch',
            name='streamer',
        ),
        migrations.AlterField(
            model_name='streamer',
            name='guild_status',
            field=models.CharField(choices=[('fry', 'Shrimp Fry (Pre-event)'), ('shrimp', 'Shrimp (1+ events)'), ('shramp', 'Shramp (4+ events)'), ('scampi', 'Scampi Shramp (OG)')], default='fry', max_length=30),
        ),
        migrations.AlterField(
            model_name='streameract',
            name='twitch_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='twitchapp.twitchaccount'),
        ),
        migrations.DeleteModel(
            name='StreamerDiscord',
        ),
        migrations.DeleteModel(
            name='StreamerMastodon',
        ),
        migrations.DeleteModel(
            name='StreamerTwitch',
        ),
    ]
