# Generated by Django 4.1.3 on 2022-12-13 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streamer', '0014_alter_streamer_shrampybot_announce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
