# Generated by Django 4.1.3 on 2022-12-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0015_alter_streamer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamer',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
