# Generated by Django 4.1.3 on 2022-12-16 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0016_alter_streamer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streameract',
            name='streamer',
        ),
    ]
