# Generated by Django 4.1.3 on 2022-12-07 22:44

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website_url', models.TextField()),
                ('broad_scope', models.TextField()),
                ('oauth_endpoint_url', models.TextField()),
                ('api_client_id', models.CharField(max_length=255)),
                ('api_secret_key', encrypted_model_fields.fields.EncryptedTextField()),
                ('api_token', encrypted_model_fields.fields.EncryptedTextField()),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
