# Generated by Django 4.1.3 on 2022-12-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='oauth_login_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='oauth_endpoint_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='website_url',
            field=models.TextField(null=True),
        ),
    ]
