# Generated by Django 4.1.3 on 2022-12-07 23:40

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_oauth_login_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='api_refresh_token',
            field=encrypted_model_fields.fields.EncryptedTextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='api_client_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='api_secret_key',
            field=encrypted_model_fields.fields.EncryptedTextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='api_token',
            field=encrypted_model_fields.fields.EncryptedTextField(null=True),
        ),
    ]
