# Generated by Django 4.1.3 on 2022-12-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_api_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='oauth_revoke_url',
            field=models.TextField(null=True),
        ),
    ]
