# Generated by Django 4.1.3 on 2022-12-08 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0004_service_oauth_revoke_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_token', encrypted_model_fields.fields.EncryptedTextField()),
                ('user_refresh_taken', encrypted_model_fields.fields.EncryptedTextField(null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='service.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
