# Generated by Django 4.1.3 on 2022-12-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_userservice_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservice',
            name='scope',
            field=models.TextField(default='read'),
        ),
    ]
