# Generated by Django 4.1.3 on 2022-12-08 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_userservice_scope'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userservice',
            old_name='user_refresh_taken',
            new_name='user_refresh_token',
        ),
    ]
