# Generated by Django 4.1.3 on 2022-12-15 01:13

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_service_streaming_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='webhooks_inbound_endpoint',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='webhooks_shared_secret',
            field=encrypted_model_fields.fields.EncryptedTextField(null=True),
        ),
    ]
