# Generated by Django 4.1.3 on 2022-12-12 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0013_rename_streamergsgfile_streameract_and_more'),
        ('discordapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StreamerDiscord',
            new_name='DiscordAccount',
        ),
    ]
