# Generated by Django 4.1.3 on 2022-12-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscordAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discord_id", models.CharField(max_length=255, unique=True)),
                (
                    "discord_name_in_guild",
                    models.CharField(max_length=255, unique=True),
                ),
                ("parsed_twitch_url", models.CharField(max_length=255)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
