# Generated by Django 4.1.3 on 2022-12-16 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discordapp', '0001_initial'),
        ('streamer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordaccount',
            name='streamer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='streamer.streamer'),
        ),
    ]
