# Generated by Django 4.1.3 on 2022-12-12 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streamer', '0012_remove_streamer_guild_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255, null=True, unique=True)),
                ('twitch_id', models.CharField(max_length=255, null=True, unique=True)),
                ('description', models.TextField(null=True)),
                ('profile_image_url', models.TextField(null=True)),
                ('offline_image_url', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('account_type', models.CharField(choices=[('', 'User'), ('staff', 'Staff'), ('global_mod', 'Global Mod'), ('admin', 'Admin')], default='', max_length=20)),
                ('broadcaster_type', models.CharField(choices=[('', 'Basic'), ('affiliate', 'Affiliate'), ('partner', 'Partner')], default='', max_length=20)),
                ('deleted', models.BooleanField(default=False)),
                ('twitch_created_at', models.DateTimeField(null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('streamer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='streamer.streamer')),
            ],
        ),
    ]
