# Generated by Django 4.1.3 on 2022-12-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_id', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('box_art_url', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
