# Generated by Django 4.1.3 on 2022-12-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitchapp', '0002_twitchcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchcategory',
            name='twitch_id',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
