# Generated by Django 4.1.3 on 2022-12-12 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitchapp', '0004_twitchcategory_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_id', models.CharField(max_length=40, unique=True)),
                ('type', models.CharField(default='live', max_length=20)),
                ('title', models.TextField(null=True)),
                ('viewer_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('language', models.CharField(max_length=20, null=True)),
                ('thumbnail_url', models.CharField(max_length=255, null=True)),
                ('is_mature', models.BooleanField(default=False)),
                ('twitch_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='twitchapp.twitchaccount')),
                ('twitch_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='twitchapp.twitchcategory')),
            ],
        ),
    ]
