# Generated by Django 4.1.3 on 2022-12-12 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twitchapp', '0005_twitchstream'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchcategory',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twitchcategory',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='twitchstream',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twitchstream',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
