# Generated by Django 4.1.3 on 2022-12-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitchapp', '0007_twitchstream_ended_at_twitchstream_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchstream',
            name='ended_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='twitchstream',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='twitchstream',
            name='started_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
