# Generated by Django 4.1.3 on 2022-12-13 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0015_alter_streamer_user'),
        ('twitchapp', '0008_alter_twitchstream_ended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchaccount',
            name='streamer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='streamer.streamer'),
        ),
    ]
