# Generated by Django 4.1.3 on 2022-12-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitchapp', '0009_alter_twitchaccount_streamer'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchstream',
            name='thumbnail_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
