# Generated by Django 4.1.3 on 2022-12-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitchapp', '0010_twitchstream_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchstream',
            name='thumbnail_image',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/<function uuid4 at 0x101a871c0>'),
        ),
    ]
