# Generated by Django 4.1.3 on 2022-12-16 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website_url', models.TextField(null=True)),
                ('broad_scope', models.TextField(null=True)),
                ('oauth_login_url', models.TextField(null=True)),
                ('oauth_endpoint_url', models.TextField(null=True)),
                ('oauth_revoke_url', models.TextField(null=True)),
                ('api_client_id', models.TextField(null=True)),
                ('api_secret_key', encrypted_model_fields.fields.EncryptedTextField(null=True)),
                ('api_token', encrypted_model_fields.fields.EncryptedTextField(null=True)),
                ('api_refresh_token', encrypted_model_fields.fields.EncryptedTextField(null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('streaming_service', models.BooleanField(default=True)),
                ('webhooks_inbound_endpoint', models.TextField(null=True)),
                ('webhooks_shared_secret', encrypted_model_fields.fields.EncryptedTextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=255, null=True)),
                ('scope', models.TextField(default='read', null=True)),
                ('user_token', encrypted_model_fields.fields.EncryptedTextField()),
                ('user_refresh_token', encrypted_model_fields.fields.EncryptedTextField(null=True)),
                ('webhooks_inbound_endpoint', models.TextField(null=True)),
                ('webhooks_shared_secret', encrypted_model_fields.fields.EncryptedTextField(null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='service.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
