# Generated by Django 4.1.3 on 2022-12-16 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streamer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255, null=True, unique=True)),
                ('twitch_id', models.CharField(max_length=255, null=True, unique=True)),
                ('description', models.TextField(null=True)),
                ('profile_image_url', models.TextField(null=True)),
                ('offline_image_url', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('account_type', models.CharField(choices=[('', 'User'), ('staff', 'Staff'), ('global_mod', 'Global Mod'), ('admin', 'Admin')], default='', max_length=20)),
                ('broadcaster_type', models.CharField(choices=[('', 'Basic'), ('affiliate', 'Affiliate'), ('partner', 'Partner')], default='', max_length=20)),
                ('deleted', models.BooleanField(default=False)),
                ('twitch_created_at', models.DateTimeField(null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('streamer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='streamer.streamer')),
            ],
        ),
        migrations.CreateModel(
            name='TwitchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_id', models.CharField(max_length=40, null=True, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('box_art_url', models.CharField(max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitchStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_id', models.CharField(max_length=40, unique=True)),
                ('type', models.CharField(default='live', max_length=20)),
                ('title', models.TextField(null=True)),
                ('viewer_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('language', models.CharField(max_length=20, null=True)),
                ('thumbnail_url', models.CharField(max_length=255, null=True)),
                ('thumbnail_image', models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/')),
                ('is_mature', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('ended_at', models.DateTimeField(db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('twitch_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='twitchapp.twitchaccount')),
                ('twitch_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='twitchapp.twitchcategory')),
            ],
        ),
    ]
