# Generated by Django 4.1.3 on 2022-12-14 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0009_alter_service_broad_scope_alter_userservice_scope'),
        ('streamer', '0015_alter_streamer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('api_info', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='service.service')),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_stream_id', models.CharField(max_length=255)),
                ('hidden', models.BooleanField(default=False)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('main_streamer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='streamer.streamer')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stream.streamingplatform')),
            ],
        ),
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(fields=('main_streamer', 'platform', 'platform_stream_id'), name='unique stream_assoc'),
        ),
    ]
