# Generated by Django 4.1.3 on 2022-12-15 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_service_streaming_service'),
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='service.service'),
        ),
        migrations.DeleteModel(
            name='StreamingPlatform',
        ),
    ]
