# Generated by Django 4.1.3 on 2022-12-15 10:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_stream_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='guid',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
