# Generated by Django 4.1.3 on 2022-12-16 11:13

from django.db import migrations, models
import gsheets.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Streamer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("identity", models.CharField(max_length=255, unique=True)),
                (
                    "guild_status",
                    models.CharField(
                        choices=[
                            ("fry", "Shrimp Fry (Pre-event)"),
                            ("shrimp", "Shrimp (1+ events)"),
                            ("shramp", "Shramp (4+ events)"),
                            ("scampi", "Scampi Shramp (OG)"),
                        ],
                        default="fry",
                        max_length=30,
                    ),
                ),
                ("shrampybot_announce", models.BooleanField(default=True)),
                ("retired", models.BooleanField(default=False)),
                ("retired_date", models.DateTimeField(null=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StreamerAct",
            fields=[
                (
                    "guid",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("visual_name", models.CharField(max_length=255)),
                ("twitch_url", models.CharField(max_length=255, null=True)),
                ("irl_location", models.CharField(max_length=255, null=True)),
                ("e_mail", models.CharField(max_length=255, null=True)),
                ("now", models.CharField(max_length=255, null=True)),
                ("next", models.CharField(max_length=255, null=True)),
                ("later", models.CharField(max_length=255, null=True)),
                ("notes", models.TextField(null=True)),
                ("alt_email", models.CharField(max_length=255, null=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
            bases=(gsheets.mixins.SheetSyncableMixin, models.Model),
        ),
    ]
